### ISSUE TITLE
does this support relationships?

### ISSUE THREAD

**Issue by manuelvillar** [manuelvillar/sequelize-auto-migrations-ng#4]
https://github.com/flexxnn/sequelize-auto-migrations/issues/5

**Comment by darita92** [comment]
just tried to use it with associations and it didn't mapped anything

**Comment by manuelvillar** [comment]
I'll need the code you have tried to use. I've tested it with this [example from sequelize repo](https://github.com/sequelize/express-example/tree/master/models) and it works as expected:
`node node_modules/sequelize-auto-migrations-ng/bin/makemigration.js`

`sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13`
` { Campaign: Campaign, Task: Task, User: User }`
` [Actions] createTable "Campaigns", deps: []`
` [Actions] createTable "Users", deps: []`
` [Actions] createTable "Tasks", deps: [Users]`
` New migration to revision 1 has been saved to file '/Users/manu/lab/sequelize-mig-testfield/migrations/1-noname.js'`

The migration is smooth too:
`sequelize db:migrate`

`Sequelize CLI [Node: 8.10.0, CLI: 4.0.0, ORM: 4.37.3]`

`Loaded configuration file "config/config.json".`
`Using environment "development".`
`sequelize deprecated String based operators are now deprecated. Please use Symbol based operators for better security, read more at http://docs.sequelizejs.com/manual/tutorial/querying.html#operators node_modules/sequelize/lib/sequelize.js:242:13`
`== 1-noname: migrating =======`
`[#0] execute: createTable`
`[#1] execute: createTable`
`[#2] execute: createTable`
`== 1-noname: migrated (0.114s)`

**Comment by darita92** [comment]
hi @manuelvillar, I was declaring the associations like:

```
sequelize.define('ModelB', {
        ...
    }, { 
        indexes: [ ... ],
        classMethods: {
            associate: (models) => {
               ModelB.belongsToMany(models.ModelA);
            }
        }
    });
```

But based on the example you provided I had to do the associations after the definition of the model like: 

```
ModelB.associate = models => {
   models.ModelB.belongsToMany(models.ModelA);
};
```

**Comment by manuelvillar** [comment]
Yes, you have to use that syntax, is one of the [changes in Sequelize v4](http://docs.sequelizejs.com/manual/tutorial/upgrade-to-v4.html).

I'm closing this feel free to reopen if you find any issue.
